### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by mufeed-ar** [aameen951/ksa_covid19#1]
I would like to thank you very much for your amazing work to get KSA COVID-19 data. I use your daily update data to refresh my follow up page of coronavirus status. But some time delay happen due to late update of the output file, I have a poor coding background but could you please teach me the way I could get the update as early as possible. Thank you

**Comment by aameen951** [comment]
I'm glad this tiny repository can help others.

I'm running a local service on my personal computer that periodically connects to MOH server and check for new updates then automatically commit/pushes the changes to GitHub.
This service is checking every 10 minutes but sometimes my computer is turned off which causes a delay of multiple hours.

What do you mean by as early as possible? Do you mean the 10 minutes delay is too much? Or are you referring to the occasional ones where the delay is multiple hours?

**Comment by mufeed-ar** [comment]
Not at all, your updates are perfect, I remember the delay happens once or twice over the past weeks, keep the good work.

Just I am wondering, if I can run that code on my personal computer, what applications do I need?

**Comment by aameen951** [comment]
The code is in inside this repository ... you need NodeJS then you can run the command `node main watch`. You also need git already installed and setup on your machine and your own fork of this repository.
Hover, I don't recommend doing that if you don't have programming skills in case something goes wrong.
